linters-settings:
  #depguard:
  #  list-type: denylist
  #  packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
  #    - github.com/sirupsen/logrus
  #  packages-with-error-message:
  #    - github.com/sirupsen/logrus: "logging is allowed only by logutils.Log"
  dupl:
    threshold: 100
  funlen:
    lines: 110
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - strings.SplitN

  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  depguard:
  # https://golangci-lint.run/usage/linters/#depguard (added 15 July 2023)
      rules:
        main:
          # List of file globs that will match this list of settings to compare against. Default: $all
          files:
            - $all #"**/internal/**/*.go"/"!$test"/"!**/*_a _file.go"
          # List of allowed packages.
          allow:
            - $gostd #matches all of go's standard library (Pulled from GOROOT)
            - github.com/faiface/beep
            - github.com/spf13/cobra
            - github.com/davidaparicio/cuc
          # Packages that are not allowed where the value is a suggestion.
          deny:
            - pkg: "reflect"
              desc: Please don't use reflect package
            - pkg: "github.com/sirupsen/logrus"
              desc: Not allowed, please use the Uber Zap library (future zap->slog)
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
# don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - revive
  # - wsl

#issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  #exclude-rules:
  #  - path: _test\.go
  #    linters:
  #      - gomnd

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  # default concurrency is a available CPU number
  concurrency: 4
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1
#  skip-dirs:
#    - test/testdata_etc # test files
# revert to go1.17 while the linters are being updated to add support for the
# generics introduced in go1.18
# go: '1.19'