name: Release (GoReleaser)

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write
  deployments: write
  id-token: write # needed for signing the images with GitHub OIDC Token **not production ready**

jobs:
  goreleaser:
    name: Prepare the binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          #registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: sigstore/cosign-installer@v3.0.1          # installs cosign
      - uses: anchore/sbom-action/download-syft@v0.13.3 # installs syft
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
